[project]
name = "trade_metrics_dashboard"
version = "0.1.0"
description = "Trade metrics dashboard"
channels = ["conda-forge"]
platforms = ["linux-64"]

[system-requirements]
linux = "5.4.0"

[tasks]

[dependencies]
pandas = ">=2.3.0,<3"
numpy = ">=2.3.1,<3"
plotly = ">=6.2.0,<7"
dash = ">=3.0.4,<4"
sqlalchemy = ">=2.0.41,<3"
dash-bootstrap-components = ">=2.0.3,<3"
pyarrow = ">=20.0.0,<21"
pandera = ">=0.24.0,<0.25"
sqlalchemy-utils = ">=0.41.2,<0.42"
dash-daq = ">=0.6.0,<0.7"

[pypi-dependencies]

[feature.dev.dependencies]
pytest = ">=8.4.0,<9"
hypothesis = ">=6.135.24,<7"

[environments]
default = { features = ["dev"], solve-group = "prod" }
prod = { features = [], solve-group = "prod" }
